### ISSUE TITLE
Project overview

### ISSUE THREAD

**Issue by eldenpark** [video-browser/prototype#6]
# Project Overview
## Deadline
**Sep 15, 2020**

We have to submit the paper with screenshots of the results.

- Known Item Search (KIS)
- Other tasks

### Webapp
Node.js, React.js

### WebApi
Node.js, Express.js

### Engine
Written in C++

## Questions
- Should we allow users to upload the video to trigger searching? This will take time and may degrade the search performance. Can we do it on CLI instead?
- Are we supposed to add a textual description to the visual KIS task? 
- Can we do the preprocessing in python?

**Comment by eldenpark** [comment]
## Type of challenges
1. KIS-Visual
2. KIS-Textual
3. AVS

## Task breakdown
### week 1
- [ ] tokenize a csv format input (csv) (@eldeni )
- [ ] word vectors (@chinmayee95 )
- [ ] categorise/classifier 
- [ ] a tree algorithm for searching//??//
- [ ] combine the frames
- [ ] classification folder has different result type - think of the way to convert it
  

#### categorize / classifier
```
one based on the labels given and one more to fetch data : color->colors; human count-> use faces;
```
